apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_URL
          
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASS

          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_NAME
