apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-abc
spec:
  accessModes:
    - ReadWriteOnce                       # ← Must match PV
  resources:
    requests:
      storage: 500Mi                      # ← Requesting 500Mi (PV has 1Gi - OK!)
  storageClassName: manual 
